# -*- coding: utf-8 -*-
"""csv_datathon_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FleUr04q9YOWCsZb8yvNHRP4UDPeVtvi
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

#traitement df PTZ
link = "/content/drive/MyDrive/2209-Data/Hackathon/TEAM MGMFR/dataframe/data_values_economiques/PTZ_CREDIT/opendataptz2022.csv"
df_PTZ = pd.read_csv(link,encoding = "ISO-8859-1",sep=",")

print(df_PTZ.head().to_markdown())

print(df_PTZ.shape)

df_PTZ['region'].value_counts()

df_PTZ_IDF=df_PTZ.loc[df_PTZ['region'] =='Île-de-France']# onfiltre qu'ile de france

print(df_PTZ_IDF.head().to_markdown())

df_PTZ_IDF=df_PTZ_IDF.loc[(df_PTZ_IDF['an'] >= 2011)] # on filtre les années après 2011

df_PTZ_IDF= df_PTZ_IDF.drop(['epci', 'zoco','durt','vtpz'], axis=1) #suppression colonnes inutiles

df_PTZ_IDF=df_PTZ_IDF.rename(columns={'cins':'code insee','vtpr':'prix total'}) # renommer les colonnes

df_PTZ_IDF= df_PTZ_IDF.drop(['vtpp'], axis=1) #suppression colonne inutile

df_PTZ_IDF=df_PTZ_IDF.rename(columns={'dtpp':'duree pret'}) # renommer les colonnes

df_PTZ_IDF=df_PTZ_IDF.rename(columns={'txno':'taux pret'}) # renommer les colonnes

print(df_PTZ_IDF.tail().to_markdown()) # renommer les colonnes

#export to csv
df_PTZ_IDF.to_csv('/content/drive/MyDrive/2209-Data/Hackathon/TEAM MGMFR/CSV/CSV A VERIFIER.df_IDF_pret.csv', index=False)