# -*- coding: utf-8 -*-
"""new_article_authors_cleaned.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sharydi5zdr8qbu74aUCwjb657bojdbv
"""

import pandas as pd
import numpy as np
import re

from google.colab import drive
drive.mount('/content/drive')

link = "/content/drive/MyDrive/2209-Data/Projets/Projet3/ACMG/Greg/new_article.csv"
new_article2 = pd.read_csv(link,sep=",")

#mettre en majuscules
new_article2['Authors'] = new_article2['Authors'].str.title()

print(new_article2.head(100).to_markdown())

new_article2.to_csv('/content/drive/MyDrive/2209-Data/Projets/Projet3/ACMG/Greg/new_articles2.csv', index=False)

