# -*- coding: utf-8 -*-
"""Test_medical_NLP_project_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AzjESgitFWJZFIBkfFBb_YcRMDhWm7bT

#MED7 test
"""

!pip install "https://huggingface.co/kormilitzin/en_core_med7_trf/resolve/main/en_core_med7_trf-any-py3-none-any.whl"

!pip install "https://huggingface.co/kormilitzin/en_core_med7_lg/resolve/main/en_core_med7_lg-any-py3-none-any.whl"

import spacy

med7 = spacy.load("en_core_med7_lg")

# create distinct colours for labels
col_dict = {}
seven_colours = ['#E6194B', '#3CB44B', '#FFE119', '#FFD8B1', '#F58231', '#F032E6', '#42D4F4']
for label, colour in zip(med7.pipe_labels['ner'], seven_colours):
    col_dict[label] = colour
options = {'ents': med7.pipe_labels['ner'], 'colors':col_dict}

text="""" background: cardiac rehabilitation (cr) can slow or reverse the progression of  cardiovascular disease (cvd). 
however, uptake of community-based cr is very low. e-cardiology, 
e-health and technology solutions for physical activity uptake and monitoring have evolved rapidly and have potential in cvd management.
 however, it is unclear what the current technology usage is of cvd patients,
 and their needs and interests for technology enabled cr. 
methods: a technology usage questionnaire was developed and completed by 
patients from a supervised ambulatory cr program and an adult congenital heart disease clinic and from two community-based cr programs. 
results were described and related with age, 
gender and educational level by spearman correlations. results: 
of 310 patients, 298 patients (77 % male; mean age 61,7 ± 14,5 years) 
completed at least 25 questions of the survey and were included in the analysis (completion rate 96 %).
 most (97 %) patients had a mobile phone and used the internet (91 %). 
heart rate monitors were used by 35 % and 68 % reported to find heart rate monitoring important when exercising at home.
 physical activity monitoring was reported by 12 % of the respondents. 
respondents were interested in cr support through internet (77 %) and mobile phone (68 %). 
many patients reported interest in game-based cr (67 %) and virtual rehabilitation (58 %). 
at least medium interest in technology enabled cr was reported by 75 % of the patients. interest decreased with increasing age (r = -0.16; p = 0.005). 
conclusions: cvd patients show interest for technology enabled home-based cr. 
our results could guide the design of a technology-based, virtual cr intervention."""

doc=med7(text)

spacy.displacy.render(doc, style='ent', jupyter=True, options=options)
[(ent.text, ent.label_) for ent in doc.ents]

"""même problème avec https://github.com/NLPatVCU/medaCy"""

#les librairies traitent plus les mots en rapport avec les médicaments et les traitements, ce qui n'est pas indiqué dans les librairies.

# importer le vocabulaire pour lemmatizer (regroupe tous les adverbes)
! python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")

##On a fait une lemmatization car on a remarqué que le med7 fesait la différence entre vitamine et vitamin alors qu'il s'agit de la même chose. La lemmeatization a amélioré la performance de med7
def transformation(texte):
  ##On remplace '-'par un espace car pour certaine molécules compoésées de deux mots séparés par un tiret le med7 ne les détectent pas en tant que DRUG
  texte = texte.replace('-',"")
  textel = [element.lemma_ for element in nlp(texte)]
  doc = med7(' '.join(textel))
  #result_color=spacy.displacy.render(doc, style='ent', jupyter=True, options=options)
  #print(result_color)
  #print([(ent.text, ent.label_) for ent in doc.ents])
  result = [ent.text for ent in doc.ents if ent.label_ == 'DRUG']
  #return ','.join(result)
  return ' '.join(result)
transformation ('Coenzyme Q10 ')

##On a fait une lemmatization car on a remarqué que le med7 fesait la différence entre vitamine et vitamin alors qu'il s'agit de la même chose. La lemmeatization a amélioré la performance de med7
def transformation(texte):
  ##On remplace '-'par un espace car pour certaine molécules compoésées de deux mots séparés par un tiret le med7 ne les détectent pas en tant que DRUG
  texte = texte.replace('-',"")
  textel = [element.lemma_ for element in nlp(texte)]
  doc = med7(' '.join(textel))
  #result_color=spacy.displacy.render(doc, style='ent', jupyter=True, options=options)
  #print(result_color)
  #print([(ent.text, ent.label_) for ent in doc.ents])
  result = [ent.text for ent in doc.ents if ent.label_ == 'DRUG']
  #return ','.join(result)
  return ' '.join(result)
transformation ('Coenzyme Q10 ')